"""primeiro

Revision ID: 3c9efe04b09c
Revises: 
Create Date: 2022-09-13 10:51:03.134021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9efe04b09c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tipo_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.String(), nullable=True))
        batch_op.drop_column('detalhes')
        batch_op.drop_column('disponivel')
        batch_op.drop_column('nome')
        batch_op.drop_column('preco')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('disponivel', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('detalhes', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacao')
        batch_op.drop_column('tipo_entrega')
        batch_op.drop_column('local_entrega')
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
